# See: https://yarnpkg.com/configuration/yarnrc

defaultSemverRangePrefix: ''
nodeLinker: 'node-modules'

packageExtensions:
  '@stylistic/eslint-plugin@*':
    dependencies:
      'typescript': '*'
  'eslint-plugin-perfectionist@*':
    dependencies:
      'typescript': '*'
  'eslint-plugin-import-x@*':
    dependencies:
      'typescript': '*'
