# See: https://yarnpkg.com/configuration/yarnrc

defaultSemverRangePrefix: ''
nodeLinker: 'node-modules'

packageExtensions:
  '@stylistic/eslint-plugin@^4':
    dependencies:
      'typescript': '*'
